name: boot_Transplant
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库文件
        uses: actions/checkout@main
      - name: -准备环境
        run: |
          sudo apt install build-essential git curl wget bison flex zip bc cpio libssl-dev python-is-python3
          mkdir "$GITHUB_WORKSPACE"/aarch64-linux-android-4.9
          cd "$GITHUB_WORKSPACE"/aarch64-linux-android-4.9
          wget https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/refs/heads/android12-gsi.tar.gz
          tar xvf android12-gsi.tar.gz
          cd ..
          mkdir "$GITHUB_WORKSPACE"/arm-linux-androideabi-4.9
          cd "$GITHUB_WORKSPACE"/arm-linux-androideabi-4.9
          wget https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+archive/refs/heads/android12-gsi.tar.gz
          tar xvf android12-gsi.tar.gz
          cd ..
          mkdir "$GITHUB_WORKSPACE"/clang-android
          cd "$GITHUB_WORKSPACE"/clang-android
          wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android12-gsi.tar.gz
          tar xvf android12-gsi.tar.gz
          cd ..
      - name: -编译内核
        run: |
          export PATH="$GITHUB_WORKSPACE/arm-linux-androideabi-4.9/bin:$GITHUB_WORKSPACE/aarch64-linux-android-4.9/bin:$GITHUB_WORKSPACE/clang-android/clang-r416183b1/bin:$PATH"
          bash build.sh lmi
      - name: -上传到Github Release
        uses: ncipollo/release-action@main
        with:
          artifacts: "${{ github.workspace }}/GithubRelease/*"
          name: "lmi"
          tag: "lmi"
          bodyFile: "${{ github.workspace }}/file.log"
          allowUpdates: true
          artifactErrorsFailBuild: true
          token: ${{ secrets.GITHUB_TOKEN }}

